# program solving and programming
### Day 13
### Date-16th may 19



# problem 1:
## problem statement
define a function to read data from a text file

### constraint


## test cases


In [ ]:
def readFileData(filename):
    f=open(filename,'r')
    #filedata=f.readline() 
    #filedata +=f.readline() # 
    filedata=f.read()
    
    f.close()
    return filedata
readFileData('DataFiles/data.txt')

In [ ]:
def readFileData(filename):
    with open(filename,'r') as f:
        for line in f:
            print(line,end='')
        #filedata=f.readline() 
    #filedata +=f.readline() # 
    #filedata=f.read()
    
    
    return 
readFileData('DataFiles/data.txt')

In [ ]:
def readFileData(filename):
    with open(filename,'r') as f:
       #for line in f:
        print(f.read())
            #print(line)
        #filedata=f.readline() 
    #filedata +=f.readline() # 
    #filedata=f.read()
    
    
    return 


def writeintofile(filename,data):
    with open(filename,'w') as f:
        f.write(data)
    return




writeintofile('DataFiles/filewrite.txt','data written into filewrite')

In [ ]:
def writeintofile(filename,data,mode):
    with open(filename,mode) as f:
        f.write(data)
    return
writeintofile('DataFiles/filewrite.txt','second line\n','a')

# problem 2:
## problem statement
define a function to generate a marks data file for 1300 students such that each marks is entered in a new line.marks range from 0 to 100(inclusive) as random numbers

### constraint


## test cases

In [7]:
import random
def generatemarksdata(n,filename):
    with open(filename,'w') as marksfile:
        for i in range(0,n):
            marks=random.randrange(0,101)
            marksfile.write(str(marks)+'\n')
    return


generatemarksdata(1300,'DataFiles/marksdata.txt')    

# problem 3:
## problem statement
generate a report on themarks data with the following
* highest mark
* lowest mark
* average mark
* number of students with distinction(>80)
* number of students with first class(>60)
* number of students with second class(>50)
* number of students with third class(>40)
* number of students failed(<40)

### constraint


## test cases

In [61]:
def generatemarksreport(filename,n):
    l=[]
    with open(filename,'r') as f:
        for line in f:
            l.append(int(line))
            
        print(max(l))
        print(min(l))
        print(sum(l)/n)
        
    failed=(sum(1 for i in l if i < 40))
    print(failed)
    
generatemarksreport('DataFiles/marksdata.txt',1300)


100
0
49.79692307692308
538


In [34]:
import re,timeit
def generatemarksreport(marksfile):
    
st = timeit.default_timer()
    marksdata = readFileData(marksfile)
    
    marksdata=re.split(r'\n',marksdata)
    print(type(marksfile[1])
          print(timeit.default_timer()-st)

generatemarksreport('marksdata.txt')

SyntaxError: invalid syntax (<ipython-input-34-e1ed9ac8ed64>, line 8)

In [ ]:
# 

In [29]:
import timeit
def squares(n):
    return n * n
st=timeit.default_timer()
li=[1,2,3,4,5,6,7]
#s=str(li)
s=list(map(str,li))
s=[float(i)for i in s]
print(timeit.default_timer()-st)
s




0.000169724999977916


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]

In [73]:
def distinction(mark):
    return mark >=80

dis=sum(map(distinction,l))
print(dis)
failed=sum((1 for i in l if i <40))
print(failed)

0
0


# external libaries

## Numpy

In [64]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(a)
type(a)

[[0 1 2]
 [3 4 5]]


numpy.ndarray

In [70]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[7,8,9]])
print(a+b)

[[ 5  7  9]
 [11 13 15]]
